# Generated by Django 3.0.3 on 2020-02-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecare', '0003_auto_20200223_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('SI', 'Single'), ('MA', 'Married'), ('DI', 'Divorce')], default='SI', max_length=2)),
                ('phone_number', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=100)),
                ('allergies', models.CharField(max_length=255)),
                ('last_time_diagnose', models.CharField(max_length=255)),
                ('health_habit_question_1', models.CharField(choices=[('NO', 'NO'), ('SOMETIMES', 'SOMETIMES'), ('ALWAYS', 'ALWAYS')], max_length=10)),
                ('health_habit_question_2', models.CharField(choices=[('NO', 'NO'), ('SOMETIMES', 'SOMETIMES'), ('ALWAYS', 'ALWAYS')], max_length=10)),
                ('health_habit_question_3', models.CharField(choices=[('NO', 'NO'), ('SOMETIMES', 'SOMETIMES'), ('ALWAYS', 'ALWAYS')], max_length=10)),
                ('self_medication_question_1', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5)),
                ('self_medication_question_2', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5)),
                ('self_medication_question_3', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5)),
                ('common_illness_question_1', models.CharField(choices=[('MAL', 'MALARIA'), ('FEV', 'FEVER'), ('TB', 'TUBERCULOSIS'), ('CHOL', 'CHOLERA'), ('OTHERS', 'OTHERS')], max_length=7)),
            ],
        ),
    ]
