# Generated by Django 3.0.3 on 2020-02-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wecare', '0004_medicalinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalinformation',
            old_name='full_name',
            new_name='username',
        ),
    ]
