# Generated by Django 3.0.3 on 2020-02-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wecare', '0005_auto_20200223_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalinformation',
            old_name='username',
            new_name='full_name',
        ),
    ]
