# Generated by Django 3.0.3 on 2020-02-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecare', '0006_auto_20200223_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
