# Generated by Django 3.0.3 on 2020-02-24 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wecare', '0007_auto_20200223_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalinformation',
            old_name='health_habit_question_1',
            new_name='adequate_physical_exercise',
        ),
        migrations.RenameField(
            model_name='medicalinformation',
            old_name='health_habit_question_2',
            new_name='adequate_sleep',
        ),
        migrations.RenameField(
            model_name='medicalinformation',
            old_name='common_illness_question_1',
            new_name='common_illness',
        ),
        migrations.RenameField(
            model_name='medicalinformation',
            old_name='self_medication_question_1',
            new_name='doctor_precription',
        ),
        migrations.RenameField(
            model_name='medicalinformation',
            old_name='self_medication_question_2',
            new_name='frequent_self_medication',
        ),
        migrations.RenameField(
            model_name='medicalinformation',
            old_name='self_medication_question_3',
            new_name='last_self_medication',
        ),
        migrations.RenameField(
            model_name='medicalinformation',
            old_name='health_habit_question_3',
            new_name='smoke_or_drink',
        ),
        migrations.AddField(
            model_name='medicalinformation',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
