version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=eHealthdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    container_name: eHealth-backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000 && python manage.py test
    depends_on:
      - db


