version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=eHealthdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "eHealthdb:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  web:
    container_name: eHealth-backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./eHealth:/app"
    # env_file:
    #   - .env
    ports:
      - "8100:8000"
    depends_on:
      - db

volumes:
  eHealthdb:
