# Generated by Django 3.0.3 on 2020-02-25 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('SI', 'Single'), ('MA', 'Married'), ('DI', 'Divorce')], default='SI', max_length=2)),
                ('phone_number', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=255)),
                ('allergies', models.CharField(max_length=255)),
                ('last_diagnose', models.CharField(max_length=255)),
                ('adequate_exercise', models.CharField(choices=[('NO', 'NO'), ('SMT', 'SOMETIMES'), ('AWS', 'ALWAYS')], max_length=3)),
                ('adequate_sleep', models.CharField(choices=[('NO', 'NO'), ('SMT', 'SOMETIMES'), ('AWS', 'ALWAYS')], max_length=3)),
                ('smoke_or_drink', models.CharField(choices=[('NO', 'NO'), ('SMT', 'SOMETIMES'), ('AWS', 'ALWAYS')], max_length=3)),
                ('last_self_medication', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=3)),
                ('frequent_self_medication', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=3)),
                ('doctor_precription', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=3)),
                ('common_illness', models.CharField(choices=[('MAL', 'MALARIA'), ('FEV', 'FEVER'), ('TUB', 'TUBERCULOSIS'), ('CHOL', 'CHOLERA'), ('OTHERS', 'OTHERS')], max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
