# Generated by Django 3.0.3 on 2020-02-29 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('DI', 'Divorce')], max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=255)),
                ('allergies', models.CharField(max_length=255)),
                ('last_diagnose', models.CharField(max_length=255)),
                ('adequate_exercise', models.CharField(choices=[('No', 'NO'), ('Sometimes', 'SOMETIMES'), ('Always', 'ALWAYS')], max_length=50)),
                ('adequate_sleep', models.CharField(choices=[('No', 'NO'), ('Sometimes', 'SOMETIMES'), ('Always', 'ALWAYS')], max_length=50)),
                ('smoke_or_drink', models.CharField(choices=[('No', 'NO'), ('Sometimes', 'SOMETIMES'), ('Always', 'ALWAYS')], max_length=50)),
                ('last_self_medication', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=50)),
                ('frequent_self_medication', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=50)),
                ('doctor_precription', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=50)),
                ('common_illness', models.CharField(choices=[('Malaria', 'MALARIA'), ('Fever', 'FEVER'), ('Tuberculosis', 'TUBERCULOSIS'), ('Cholera', 'CHOLERA'), ('Others', 'OTHERS')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
