# Generated by Django 3.0.3 on 2020-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinformation',
            name='adequate_exercise',
            field=models.CharField(choices=[('No', 'No'), ('Sometimes', 'Sometimes'), ('Always', 'Always')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='adequate_sleep',
            field=models.CharField(choices=[('No', 'No'), ('Sometimes', 'Sometimes'), ('Always', 'Always')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='common_illness',
            field=models.CharField(choices=[('Malaria', 'Malaria'), ('Fever', 'Fever'), ('Tuberculosis', 'Tuberculosis'), ('Cholera', 'Cholera'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='doctor_precription',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='frequent_self_medication',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='last_self_medication',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorce', 'Divorce')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='smoke_or_drink',
            field=models.CharField(choices=[('No', 'No'), ('Sometimes', 'Sometimes'), ('Always', 'Always')], max_length=50),
        ),
    ]
