# Generated by Django 3.0.3 on 2020-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinformation',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
