# Generated by Django 3.0.3 on 2020-02-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinformation',
            name='adequate_exercise',
            field=models.CharField(choices=[('No', 'NO'), ('Sometimes', 'SOMETIMES'), ('Always', 'ALWAYS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='adequate_sleep',
            field=models.CharField(choices=[('No', 'NO'), ('Sometimes', 'SOMETIMES'), ('Always', 'ALWAYS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='common_illness',
            field=models.CharField(choices=[('Malaria', 'MALARIA'), ('Fever', 'FEVER'), ('Tuberculosis', 'TUBERCULOSIS'), ('Cholera', 'CHOLERA'), ('Others', 'OTHERS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='doctor_precription',
            field=models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='frequent_self_medication',
            field=models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='last_self_medication',
            field=models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('DI', 'Divorce')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='smoke_or_drink',
            field=models.CharField(choices=[('No', 'NO'), ('Sometimes', 'SOMETIMES'), ('Always', 'ALWAYS')], max_length=50),
        ),
    ]
