name: CI with Github

# On events
on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop

# jobs to run
jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:

            # step 1: set up python 
            - name: Set up python latest version
              uses: actions/setup-python@v2
        
            # step 2: Checkout repository code
            - name: Checkout code into workspace directory
              uses: actions/checkout@v2

            # step 3: Install dependencies
            - name: Install all dependencies
              run: pip install -r requirements.txt
            
            # step 4: Run test
            - name: Run all tests
              env:
                SECRET_KEY: ${{ secrets.SECRET_KEY }}
                DEBUG: ${{ secrets.DEBUG }}
                API_KEY: ${{ secrets.API_KEY }}
                API_SECRET: ${{ secrets.API_SECRET }}
                CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
                DBPASSWD: ${{ secrets.DBPASSWD }}
                DBUSER: ${{ secrets.DBUSER }}
              run: |
                cd eHealth
                python manage.py test
